version: '3.1'
services:
    nginx:
## pull nginx:latest
        image: nginx:latest
## name it nginx
        container_name: nginx
## make sure flask is first
        depends_on:
            - flask
## mapp our conf over default
        volumes:
            - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./conf/server.crt:/etc/nginx/ssl/server.crt
            - ./conf/server.key:/etc/nginx/ssl/server.key
## internal network
        networks:
            - flask-net
## forward from docker host 80->80
        ports:
            - 443:443
            #- 80:80
    flask:
## build flask base on Dockerfile
        build:
            context: ./
            dockerfile: Dockerfile
## name it flask tag 0.0.1
        image: flask:0.0.1
        container_name: flask
## a means to overload the application code during runtime
        #volumes:
        #  - ./apps:/opt/apps/
## internal network
        networks:
            flask-net:
## ref name in nginx.conf flask-app
                aliases:
                    - flask-app
## forward from docker host 8080->5000
## only really neeed for debug, nginx will proxy to 5000 direct
        #ports:
        #    - 8080:5000
##internal network
networks:
    flask-net:
